# Generated by Django 2.2.2 on 2019-06-29 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='peopleNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='pcroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jryapp.PCRoom'),
        ),
        migrations.DeleteModel(
            name='PeopleNumber',
        ),
    ]
