# Generated by Django 2.2.2 on 2019-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jryapp', '0002_auto_20190629_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='contact',
        ),
        migrations.AddField(
            model_name='reservation',
            name='groupName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
